### PR TITLE
Fix For Napping API Change

### PR DESCRIPTION
**Pull request by dax0**
Fix for issue #80

### CODE REVIEW

**Comment by dax0** [comment]
This is a great example why we need a defacto dependency manager that can pin versions

**Comment by jadengore** [comment]
@dax0 Having the same problem, definitely need this fix. I've been using [Nut](http://github.com/jingweno/nut) for vendoring dependencies and it works well, but it seems that in-dependency dependencies are a still insurmountable challenge.

Hopefully this will be merged soon!

**Comment by jmcvetta** [comment]
What we really need is a programmatic API versioner. I accepted that pull
request to Napping, and did not notice that it changed the API and broke
compatibility with existing consumers. Thanks to build caching, the CI
tools did not notice it either.  Ugh.

My solution is to undo the Napping API change.  In progress.

**Comment by jadengore** [comment]
Thanks @jmcvetta, you've been really responsive to the many PR's over the past couple of days. The Go community really appreciates it :+1:

**Comment by jmcvetta** [comment]
@jadengore No problem, happy to help.  If you know any companies that need some remote freelance Go programming done, send them my direction.  :)

The changes to Napping have been reverted.  Tests on Neoism are all passing for me locally, and on a CircleCI build without cache.  Please confirm everything is working for you again.

**Comment by jadengore** [comment]
@jmcvetta Tests are green on my end, thanks for fixing that!

**Pull request closed without merging**
